# Usa l'immagine ufficiale di Node.js come base
FROM node:latest

# Imposta la directory di lavoro all'interno del container
WORKDIR /app

# Copia il file package.json e package-lock.json nella directory di lavoro
COPY package*.json ./

# Installa le dipendenze del progetto
RUN npm install

# Copia tutti i file e le cartelle del progetto nella directory di lavoro del container
COPY . .

# Espone la porta sulla quale il server Express ascolta
EXPOSE 3000

# Comando per avviare il server
CMD ["npm", "start"]