GET http://localhost:3000/ideas/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiZGF2aWRlIiwiaWF0IjoxNzE3Nzc2Nzk0LCJleHAiOjE3MTc4NjMxOTR9.XV6QkQdiMCxNYnzGi1B0Xf4ZsTZt4Q6WGgrxnLn2I_U